require('dotenv').config();
const db = require('./src/config/database');
const User = require('./src/models/User');
const OTP = require('./src/models/OTP');
const authService = require('./src/services/authService');

const runFullAuthAudit = async () => {
  console.log('================================================================');
  console.log('=== STARTING CAPACITY CONNECT AUTHENTICATION & OTP TEST SUITE ===');
  console.log('================================================================\n');

  if (db.initializeDatabase) {
    try {
      await db.initializeDatabase();
    } catch (err) {
      console.log('[INIT] Database init fallback to memory store');
    }
  }

  let passed = 0;
  let failed = 0;

  const assert = (condition, title, details = '') => {
    if (condition) {
      console.log(`[PASS] ✅ ${title}`);
      passed++;
    } else {
      console.error(`[FAIL] ❌ ${title} - ${details}`);
      failed++;
    }
  };

  try {
    // -----------------------------------------------------------------
    // TEST A: SIGNUP FLOW
    // -----------------------------------------------------------------
    console.log('--- TEST A: SIGNUP NEW USER FLOW ---');
    const signupEmail = `signup_test_${Date.now()}@example.com`;
    const signupPass = 'Password123!';
    
    const signupRes = await authService.signup({
      full_name: 'Signup Test User',
      email: signupEmail,
      password: signupPass,
      role: 'trainee',
    });

    assert(
      signupRes.requiresEmailVerification === true && signupRes.email === signupEmail,
      'Signup creates unverified user and returns requiresEmailVerification: true'
    );
    assert(signupRes.emailDelivered === true, 'Signup OTP email provider accepted live dispatch');

    const signupUser = await User.findByEmail(signupEmail);
    assert(signupUser && !signupUser.email_verified, 'Signup user stored in DB with email_verified = false');

    // Retrieve OTP for verification
    const signupOtpDoc = await OTP.findActiveOTP({ email: signupEmail, purpose: 'email_verification' });
    assert(signupOtpDoc !== null, 'Signup OTP record exists in DB');

    let signupOtpCode = signupOtpDoc?.otpCode;
    if (!signupOtpCode && signupOtpDoc?.otpHash) {
      for (let code = 100000; code <= 999999; code++) {
        if (OTP.hashOTP(code) === signupOtpDoc.otpHash) {
          signupOtpCode = String(code);
          break;
        }
      }
    }
    assert(signupOtpCode !== undefined, 'Retrieved valid signup 6-digit OTP code');

    const signupVerifyRes = await authService.verifyEmailOTP(signupEmail, signupOtpCode);
    assert(signupVerifyRes.token && signupVerifyRes.user?.email_verified === true, 'Verifying signup OTP sets email_verified = true & issues token');

    // -----------------------------------------------------------------
    // TEST B: LOGIN UNVERIFIED USER FLOW (CRITICAL TEST)
    // -----------------------------------------------------------------
    console.log('\n--- TEST B: LOGIN UNVERIFIED USER FLOW (CRITICAL FIX TEST) ---');
    const unverifiedEmail = `unverified_test_${Date.now()}@example.com`;
    const unverifiedPass = 'Password123!';

    // Create unverified user directly in DB
    const unverifiedUser = await User.create({
      email: unverifiedEmail,
      password_hash: await require('./src/utils/password').hashPassword(unverifiedPass),
      full_name: 'Unverified Login User',
      role: 'trainee',
      email_verified: false,
    });
    assert(unverifiedUser && !unverifiedUser.email_verified, 'Created unverified user directly in database');

    // Perform Login as unverified user
    try {
      await authService.login({ email: unverifiedEmail, password: unverifiedPass });
      assert(false, 'Login for unverified user should throw requiresEmailVerification error');
    } catch (err) {
      assert(
        err.statusCode === 403 && err.requiresEmailVerification === true,
        'Login for unverified user throws HTTP 403 requiresEmailVerification: true'
      );
    }

    // Verify OTP was created and email service was called
    const loginOtpDoc = await OTP.findActiveOTP({ email: unverifiedEmail, purpose: 'email_verification' });
    assert(loginOtpDoc !== null, 'Login flow generated and stored active OTP in database for unverified user');

    let loginOtpCode = loginOtpDoc?.otpCode;
    if (!loginOtpCode && loginOtpDoc?.otpHash) {
      for (let code = 100000; code <= 999999; code++) {
        if (OTP.hashOTP(code) === loginOtpDoc.otpHash) {
          loginOtpCode = String(code);
          break;
        }
      }
    }
    assert(loginOtpCode !== undefined, 'Retrieved valid 6-digit OTP code generated by login flow');

    // Verify OTP generated during login
    const loginVerifyRes = await authService.verifyEmailOTP(unverifiedEmail, loginOtpCode);
    assert(loginVerifyRes.token && loginVerifyRes.user?.email_verified === true, 'OTP generated by login flow can be verified by /verify-email');

    // Login after verification
    const verifiedLoginRes = await authService.login({ email: unverifiedEmail, password: unverifiedPass });
    assert(verifiedLoginRes.token && verifiedLoginRes.user?.email_verified === true, 'After verification, login succeeds immediately without OTP');

    // -----------------------------------------------------------------
    // TEST C: LOGIN VERIFIED USER FLOW
    // -----------------------------------------------------------------
    console.log('\n--- TEST C: LOGIN VERIFIED USER FLOW ---');
    const verifiedUserRes = await authService.login({ email: signupEmail, password: signupPass });
    assert(verifiedUserRes.token !== undefined, 'Verified user login succeeds and issues JWT token without OTP prompt');

    // -----------------------------------------------------------------
    // TEST D: UNKNOWN USER LOGIN
    // -----------------------------------------------------------------
    console.log('\n--- TEST D: UNKNOWN USER LOGIN FLOW ---');
    try {
      await authService.login({ email: `unknown_${Date.now()}@domain.com`, password: 'Password123!' });
      assert(false, 'Login with non-existent email should fail');
    } catch (err) {
      assert(err.statusCode === 404 && err.accountNotFound === true, 'Login with non-existent email returns HTTP 404 accountNotFound without creating user');
    }

    // -----------------------------------------------------------------
    // TEST E: WRONG PASSWORD LOGIN
    // -----------------------------------------------------------------
    console.log('\n--- TEST E: WRONG PASSWORD LOGIN FLOW ---');
    try {
      await authService.login({ email: signupEmail, password: 'WrongPassword999!' });
      assert(false, 'Login with wrong password should fail');
    } catch (err) {
      assert(err.statusCode === 401, 'Login with wrong password returns HTTP 401 Invalid email or password');
    }

    console.log('\n================================================================');
    console.log(`FULL AUTHENTICATION TEST SUITE FINISHED: ${passed} PASSED, ${failed} FAILED`);
    console.log('================================================================');
  } catch (err) {
    console.error('Fatal test execution error:', err);
  } finally {
    process.exit(failed === 0 ? 0 : 1);
  }
};

runFullAuthAudit();
